# Generated by Django 5.2.11 on 2026-05-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_attempt_author_alter_question_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='author',
        ),
    ]
