# Generated by Django 5.2.11 on 2026-05-19 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_attempt_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('GENERIC', 'Generic'), ('EXAM_VIOLATION', 'Exam Violation'), ('QUIZ_PUBLISHED', 'Quiz Published'), ('QUIZ_UPCOMING', 'Quiz Upcoming'), ('ATTEMPT_START', 'Attempt Started'), ('ATTEMPT_SUBMITTED', 'Attempt Submitted'), ('SCORE_RELEASED', 'Score Released'), ('SYSTEM_ALERT', 'System Alert'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, default='GENERIC', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('firebase_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['recipient', '-id'], name='exam_notifi_recipie_4b8fe7_idx'), models.Index(fields=['recipient', 'read_at'], name='exam_notifi_recipie_748f05_idx')],
            },
        ),
    ]
