# Generated by Django 5.2.11 on 2026-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('ongoing', 'Ongoing'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='ready', max_length=20),
        ),
    ]
