export { default as Dashboard } from './Dashboard';
export { default as QuizList } from './QuizList';
export { default as QuizDetail } from './QuizDetail';
export { default as TakeQuiz } from './TakeQuiz';
export { default as Result } from './Result';
export { default as History } from './History';
export { default as PersonalInfo } from './PersonalInfo';
export { default as Settings } from './Settings';
export { default as StudentClassGroups } from './ClassGroups';
