export { default as Dashboard } from './Dashboard';
export { default as Users } from './Users';
export { default as Quizzes } from './MyQuizzes';
export { default as Questions } from './Questions';
export { default as Attempts } from './Attempts';
export { default as Analytics } from './Analytics';
export { default as Subjects } from './Subjects';
export { default as ClassGroups } from './ClassGroups';
export { default as Files } from './Files';
